services:
  drupal:
    image: ghcr.io/soda-collections-objects-data-literacy/wisski-base-image:${WISSKI_BASE_IMAGE_VERSION}
    container_name: ${SERVICE_NAME}--drupal
    volumes:
      # this path is important for snapshots of the wisski components
      - drupal-root:/opt/drupal
      - soda_scs_manager_deployment_shared-data:/var/private-files
    args:
      USER_GROUPS: ${USER_GROUPS}
    environment:
      DB_HOST: ${DB_HOST}
      DB_DRIVER: ${DB_DRIVER}
      DEFAULT_GRAPH: ${DEFAULT_GRAPH}
      DOMAIN: ${DOMAIN}
      DRUPAL_USER: ${DRUPAL_USER}
      DRUPAL_PASSWORD: ${DRUPAL_PASSWORD}
      DRUPAL_TRUSTED_HOST: ${DRUPAL_TRUSTED_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      KEYCLOAK_ADMIN_GROUP: ${KEYCLOAK_ADMIN_GROUP}
      KEYCLOAK_USER_GROUP: ${KEYCLOAK_USER_GROUP}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      OPENID_CONNECT_CLIENT_SECRET: ${OPENID_CONNECT_CLIENT_SECRET}
      SERVICE_NAME: ${SERVICE_NAME}
      SITE_NAME: ${SITE_NAME}
      TS_PASSWORD: ${TS_PASSWORD}
      TS_READ_URL: ${TS_READ_URL}
      TS_REPOSITORY: ${TS_REPOSITORY}
      TS_TOKEN: ${TS_TOKEN}
      TS_USERNAME: ${TS_USERNAME}
      TS_WRITE_URL: ${TS_WRITE_URL}
      WISSKI_FLAVOURS: ${WISSKI_FLAVOURS}
      WISSKI_BASE_IMAGE_VERSION: ${WISSKI_BASE_IMAGE_VERSION}

    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=https-redirect"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web,websecure"
      - "traefik.http.routers.${SERVICE_NAME}.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}.tls.certresolver=le"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=80"

networks:
  reverse-proxy:
    external: true

volumes:
  drupal-root:
  soda_scs_manager_deployment_shared-data:
    external: true

